### ISSUE TITLE
5 Sketches of Randomness

### ISSUE THREAD

**Issue by austince** [jeffThompson/CreativeProgramming1#50]
I won't be there for class tomorrow but if any type of feedback is possible I would greatly appreciate it! 🙏 
@jeffThompson + all, thank you!
[randomness.zip](https://github.com/jeffThompson/CreativeProgramming1/files/1396719/randomness.zip)

**Comment by jeffThompson** [comment]
Seems only two of your sketches have images saved, the others are just code. Can you re-export and upload?

**Comment by austince** [comment]
Darn, here's a version with all the images.
[randomness.zip](https://github.com/jeffThompson/CreativeProgramming1/files/1399650/randomness.zip)

**Comment by austince** [comment]
Here's the readme (looks better on GitHub):

# 5 Sketchess of Randomness
Austin Cawley-Edwards  

## 1 - Recursive Dots
Toying with an initial sketch I did for the recursion assignment. Layers compilmentary dots on top of eachother. 
The first dot should be a combination of all of the colors and then they should branch out from there, ultimately moving towards the same color.  


## 2 - Circular Noise
Taking the Perlin motion and applying it to other shapes I've been trying to make this semester.  
Noisey, wavy, distored circles are awesome, and this lets me create a bunch of them.


## 3 - Random Seeds based on your file hoarding + I.P. address
Allowed myself to dive deeper into the technical side of this one. (1 / 5 sketches == 20%??)

Using a base example to experiment with seeding the random generator.  

File Hoarding:
Counts the number of files you have in popular directories on your computer. Forces the user to interact with another interface of the computer to change the seed.
Can count:
* Home Directory (v. slow)
* Desktop
* Downloads

IP Address:
Instead of interacting with the computer, the user will have to interact with the outside world, moving networks (and usually locations) to change the seed.


## 4 - Scribbled and Curved Motion
A play on Brownian motion, scribbles in a curved but erradic way across the screen. The stroke and color change.  
Color change is constant with time.  
Stroke change is in proportion to how much has changed since last time.  

All the colors are slightly transluecent, so maybe if run long enough the result might be a mess of brown. 


## 5 - Arcs Overlaid
Draws translucent arcs in a horizontal line with random overlay and height. 
Also draws a mesh layer of hollowed out arcs over the top of everything. They are also governed by similar randomness.
Saves as a pdf and png.
